### ISSUE TITLE
first run error on fresh initialised SvelteKit template

### ISSUE THREAD

**Issue by shedali** [svelte-add/mdsvex#15]
reproducible for me with the following steps

```
npm init svelte@next sveltekit-mdsvex-debug; \
cd sveltekit-mdsvex-debug\
npm install \ 
npx svelte-add mdsvex
```

```
 npx svelte-add mdsvex
➕ Svelte Add
The project directory you're giving to this command cannot be determined to be guaranteed fresh — maybe it is, maybe it isn't. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.

mdsvex
file:///Users/franz/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/index.js:324
                reject(new Error(body));
                       ^

Error: (node:38145) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:38153) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)

    at Socket.<anonymous> (file:///Users/franz/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/index.js:324:10)
    at Socket.emit (node:events:377:35)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

node v16.2.0
npm 7.13.0

**Comment by ohbob** [comment]
Tried to do the same on svelte-kit project.

node: v14.16.0
npm: 6.14.11
```
npx svelte-add mdsvex
npx: installed 61 in 11.655s
➕ Svelte Add
The project directory you're giving to this command cannot be determined to be guaranteed fresh — maybe it is, maybe it isn't. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.

mdsvex
(node:64090) UnhandledPromiseRejectionWarning: Error: npx: installed 203 in 3.954s
npx: command not found: use-preset

    at Socket.<anonymous> (file:///Users/def/.npm/_npx/64090/lib/node_modules/svelte-add/index.js:324:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:64090) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:64090) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by shedali** [comment]
I should add that in my case, running npx svelte-add mdsvex again results in success...
